version: "3"

services:
  guestbook:
    image: k8s.gcr.io/guestbook:v3
    ports:
      - "3000:3000"
  redis-master:
    image: k8s.gcr.io/redis:e2e
    ports:
      - "3001:6379"
  redis-slave:
    image: k8s.gcr.io/redis-slave:v2
    ports:
      - "3002:6379"
 