apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-slave
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: devlop
  destination:
    namespace: devlop
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: redis-slave
    namespace: devlop
    jsonPointers:
    - /spec/replicas
  source:
    repoURL: https://github.com/naokivandit/k8s-guestbook.git
    targetRevision: master
    path: 'k8s/redis-slave/overlays/dev'
